export const courseListData = {
  "courses": [
    {
      "course_id": 1,
      "course_name": "Introduction to Programming",
      "instructor_name": "John Doe",
      "description": "Learn the basics of programming with Python.",
      "enrollment_status": "Open",
      "course_duration": "6 weeks",
      "schedule": "Mon, Wed, Fri - 10:00 AM to 12:00 PM",
      "location": "Room 101, CS Building",
      "pre_requisites": "None",
      "syllabus": [
        "Week 1: Introduction to Python",
        "Week 2: Data Types and Variables",
        "Week 3: Control Structures",
        "Week 4: Functions and Modules",
        "Week 5: Working with Files",
        "Week 6: Final Project"
      ],
      "price": "$ 200",
      "image_url": "/public/images/pic-1.jpg",
      "course_image_url" : "https://johnthecomputerman.co.uk/storage/2021/05/introtoprogramming-190909184629-thumbnail-4.jpg"
    },
    {
      "course_id": 2,
      "course_name": "Data Structures and Algorithms",
      "instructor_name": "Jane Smith",
      "description": "Deep dive into data structures and algorithms with hands-on examples.",
      "enrollment_status": "Closed",
      "course_duration": "8 weeks",
      "schedule": "Tue, Thu - 2:00 PM to 4:00 PM",
      "location": "Room 202, CS Building",
      "pre_requisites": "Introduction to Programming",
      "syllabus": [
        "Week 1: Arrays and Linked Lists",
        "Week 2: Stacks and Queues",
        "Week 3: Trees and Graphs",
        "Week 4: Sorting Algorithms",
        "Week 5: Searching Algorithms",
        "Week 6: Dynamic Programming",
        "Week 7: Greedy Algorithms",
        "Week 8: Final Project"
      ],
      "price": "$ 300",
      "image_url": "/public/images/pic-3.jpg",
      "course_image_url" : "https://miro.medium.com/v2/resize:fit:1400/1*4ZcW5tSdizlbtDQyVpRTuA.jpeg"
    },
    {
      "course_id": 3,
      "course_name": "Web Development with React",
      "instructor_name": "Mike Johnson",
      "description": "Build interactive web applications using React.",
      "enrollment_status": "Open",
      "course_duration": "6 weeks",
      "schedule": "Mon, Wed, Fri - 1:00 PM to 3:00 PM",
      "location": "Room 303, IT Building",
      "pre_requisites": "HTML, CSS, JavaScript",
      "syllabus": [
        "Week 1: Introduction to React",
        "Week 2: Components and Props",
        "Week 3: State Management",
        "Week 4: React Hooks",
        "Week 5: Routing with React Router",
        "Week 6: Final Project"
      ],
      "price": "$ 250",
      "image_url": "/public/images/pic-4.jpg",
       "course_image_url" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcR5U16C8yXgBpl7-Bc7Itjx3_LRl425zINA&s"
    },
    {
      "course_id": 4,
      "course_name": "Advanced Java Programming",
      "instructor_name": "Susan Lee",
      "description": "Master advanced concepts in Java and build robust applications.",
      "enrollment_status": "In Progress",
      "course_duration": "10 weeks",
      "schedule": "Mon, Wed - 4:00 PM to 6:00 PM",
      "location": "Room 404, CS Building",
      "pre_requisites": "Java Programming Basics",
      "syllabus": [
        "Week 1: Advanced OOP Concepts",
        "Week 2: Multithreading",
        "Week 3: Generics and Collections",
        "Week 4: Lambda Expressions",
        "Week 5: Stream API",
        "Week 6: Networking in Java",
        "Week 7: JavaFX for GUI",
        "Week 8: Java Persistence API",
        "Week 9: Microservices with Spring Boot",
        "Week 10: Final Project"
      ],
      "price": "$ 400",
      "image_url": "/public/images/pic-5.jpg",
       "course_image_url" : "https://media.geeksforgeeks.org/wp-content/uploads/20230823152056/What-is-Advance-JAVA.png"
    },
    {
      "course_id": 5,
      "course_name": "Database Management Systems",
      "instructor_name": "David Brown",
      "description": "Learn about database design, SQL, and management systems.",
      "enrollment_status": "Open",
      "course_duration": "8 weeks",
      "schedule": "Tue, Thu - 9:00 AM to 11:00 AM",
      "location": "Room 505, IT Building",
      "pre_requisites": "None",
      "syllabus": [
        "Week 1: Introduction to Databases",
        "Week 2: Entity-Relationship Model",
        "Week 3: SQL Basics",
        "Week 4: Advanced SQL",
        "Week 5: Normalization",
        "Week 6: Transactions and Concurrency",
        "Week 7: NoSQL Databases",
        "Week 8: Final Project"
      ],
      "price": "$ 350",
      "image_url": "/public/images/pic-6.jpg",
       "course_image_url" : "https://img.freepik.com/premium-vector/dbms-database-management-system-concept-with-big-words-people-surrounded-by-related-icon-with-blue-color-style_25156-1382.jpg"
    },
    {
      "course_id": 6,
      "course_name": "Machine Learning Basics",
      "instructor_name": "Emily White",
      "description": "An introductory course on machine learning and its applications.",
      "enrollment_status": "In Progress",
      "course_duration": "12 weeks",
      "schedule": "Mon, Wed - 3:00 PM to 5:00 PM",
      "location": "Room 606, AI Building",
      "pre_requisites": "Python Programming, Statistics",
      "syllabus": [
        "Week 1: Introduction to Machine Learning",
        "Week 2: Supervised Learning",
        "Week 3: Unsupervised Learning",
        "Week 4: Regression Models",
        "Week 5: Classification Models",
        "Week 6: Neural Networks",
        "Week 7: Deep Learning Basics",
        "Week 8: Model Evaluation",
        "Week 9: Feature Engineering",
        "Week 10: Hyperparameter Tuning",
        "Week 11: Deployment of ML Models",
        "Week 12: Final Project"
      ],
      "price": "$ 500",
      "image_url": "/public/images/pic-7.jpg",
       "course_image_url" : "https://miro.medium.com/v2/resize:fit:1400/1*cG6U1qstYDijh9bPL42e-Q.jpeg"
    },
    {
      "course_id": 7,
      "course_name": "Cybersecurity Fundamentals",
      "instructor_name": "Kevin Harris",
      "description": "Understand the basics of cybersecurity and how to protect systems.",
      "enrollment_status": "Closed",
      "course_duration": "6 weeks",
      "schedule": "Tue, Thu - 10:00 AM to 12:00 PM",
      "location": "Room 707, Security Building",
      "pre_requisites": "None",
      "syllabus": [
        "Week 1: Introduction to Cybersecurity",
        "Week 2: Network Security",
        "Week 3: Cryptography Basics",
        "Week 4: Cyber Threats",
        "Week 5: Security Protocols",
        "Week 6: Final Project"
      ],
      "price": "$ 300",
      "image_url":"/public/images/pic-7.jpg",
       "course_image_url" : "https://thumbs.dreamstime.com/b/data-protection-cyber-security-privacy-business-internet-technology-concept-153621251.jpg"
    },
    {
      "course_id": 8,
      "course_name": "Cloud Computing with AWS",
      "instructor_name": "Laura Wilson",
      "description": "Learn cloud computing concepts and AWS services.",
      "enrollment_status": "Open",
      "course_duration": "8 weeks",
      "schedule": "Mon, Wed - 1:00 PM to 3:00 PM",
      "location": "Room 808, Cloud Building",
      "pre_requisites": "None",
      "syllabus": [
        "Week 1: Introduction to Cloud Computing",
        "Week 2: AWS Core Services",
        "Week 3: Networking in AWS",
        "Week 4: Storage in AWS",
        "Week 5: Security in AWS",
        "Week 6: Deploying Applications on AWS",
        "Week 7: Monitoring and Management in AWS",
        "Week 8: Final Project"
      ],
      "price": "$ 450",
      "image_url": "/public/images/pic-8.jpg",
       "course_image_url" : "/public/images/post-2-2.png"
    },
    {
      "course_id": 9,
      "course_name": "Mobile App Development with Flutter",
      "instructor_name": "Chris Martin",
      "description": "Build cross-platform mobile apps using Flutter.",
      "enrollment_status": "In Progress",
      "course_duration": "10 weeks",
      "schedule": "Tue, Thu - 4:00 PM to 6:00 PM",
      "location": "Room 909, Mobile Lab",
      "pre_requisites": "Basic Programming Knowledge",
      "syllabus": [
        "Week 1: Introduction to Flutter",
        "Week 2: Dart Programming Language",
        "Week 3: Building UI with Flutter",
        "Week 4: State Management in Flutter",
        "Week 5: Navigation and Routing",
        "Week 6: Working with APIs",
        "Week 7: Firebase Integration",
        "Week 8: Animations in Flutter",
        "Week 9: Testing and Debugging",
        "Week 10: Final Project"
      ],
      "price": "$ 400",
      "image_url": "/public/images/pic-9.jpg",
       "course_image_url" : "https://www.biztechcs.com/wp-content/uploads/2021/04/Why-Flutter-is-Better-for-App-Development-jpg-webp.webp"
    },
      {
        "course_id": 10,
        "course_name": "Introduction to Artificial Intelligence",
        "instructor_name": "Patricia Green",
        "description": "Explore the fundamental concepts of Artificial Intelligence.",
        "enrollment_status": "Open",
        "course_duration": "8 weeks",
        "schedule": "Mon, Wed - 9:00 AM to 11:00 AM",
        "location": "Room 1010, AI Building",
        "pre_requisites": "None",
        "syllabus": [
          "Week 1: History of AI",
          "Week 2: AI Concepts and Terminology",
          "Week 3: Problem Solving and Search",
          "Week 4: Knowledge Representation",
          "Week 5: Machine Learning Overview",
          "Week 6: Natural Language Processing",
          "Week 7: AI in Robotics",
          "Week 8: Final Project" 
        ],
        "price": "$ 500",
        "image_url": "/public/images/pic-2.jpg",
        "course_image_url" : "https://miro.medium.com/v2/resize:fit:900/1*57YDg0EsnSBYsTnwYPkSDg.jpeg"
      }
    ]
    }

